/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package nezet;

import java.awt.Component;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import model.Karakter;

/**
 *
 * @author matex
 */
public class HarcosVarazsloGUI extends javax.swing.JFrame {

    private Karakter varazslo = new Karakter(1, "Varázsló");
    private Karakter harcos = new Karakter(3, "Harcos");
    private JButton[] palya;
    private Icon varazsloIcon = new ImageIcon("kepek/blackmage.png");
    private Icon harcosIcon = new ImageIcon("kepek/warrior.png");
    private Icon harcIcon = new ImageIcon("kepek/harc.png");

    /**
     * Creates new form HarcosVarazsloGUI
     */
    public HarcosVarazsloGUI() {
        initComponents();
        palyaSzerzes();
        Boolean valakiHalottE= false;
        while (!valakiHalottE) {
            varazslo.mozgas();
            harcos.mozgas();
            //VEleteroJelz.setText(Integer.toString(varazslo.getEletero()));
            //HEleteroJelz.setText(Integer.toString(harcos.getEletero()));
            VEleteroJelz.setText(Integer.toString(varazslo.getPozicio()));
            HEleteroJelz.setText(Integer.toString(harcos.getPozicio()));
            if (varazslo.getPozicio() == harcos.getPozicio()) {
                harc();
                //palya[varazslo.getPozicio()].setIcon(harcIcon);
                palya[varazslo.getPozicio()].setText("X");
                VEleteroJelz.setText(Integer.toString(varazslo.getPozicio()));
                HEleteroJelz.setText(Integer.toString(harcos.getPozicio()));
            } else {
                //palya[harcos.getPozicio()].setIcon(harcosIcon);
                //palya[varazslo.getPozicio()].setIcon(varazsloIcon);
                palya[harcos.getPozicio()].setText("H");
                palya[varazslo.getPozicio()].setText("V");

            }
            valakiHalottE = (harcos.getEletero()>=0 || varazslo.getEletero()>=0);
        }

    }

    private void palyaSzerzes() {
        palya = new JButton[3];
        Component[] comps = PalyaPanel.getComponents();
        for (int i = 0; i < comps.length; i++) {
            palya[i] = (JButton) comps[i];
        }
    }

    private void palyaUrites() {
        for (int i = 0; i < palya.length; i++) {
            palya[i].setText("");
        }
    }

    private void harc() {
        varazslo.sebzes();
        harcos.sebzes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        gombokPanel = new javax.swing.JPanel();
        UjJatekGomb = new javax.swing.JButton();
        KovetkezoKorGomb = new javax.swing.JButton();
        EleterokPanel = new javax.swing.JPanel();
        VEleteroJelz = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        HEleteroJelz = new javax.swing.JLabel();
        PalyaPanel = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        UjJatekGomb.setText("Új játék");
        UjJatekGomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UjJatekGombActionPerformed(evt);
            }
        });

        KovetkezoKorGomb.setText("Következő kör");
        KovetkezoKorGomb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KovetkezoKorGombActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout gombokPanelLayout = new javax.swing.GroupLayout(gombokPanel);
        gombokPanel.setLayout(gombokPanelLayout);
        gombokPanelLayout.setHorizontalGroup(
            gombokPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gombokPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(KovetkezoKorGomb)
                .addGap(151, 151, 151)
                .addComponent(UjJatekGomb)
                .addContainerGap())
        );
        gombokPanelLayout.setVerticalGroup(
            gombokPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(gombokPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(gombokPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(KovetkezoKorGomb)
                    .addComponent(UjJatekGomb))
                .addContainerGap())
        );

        VEleteroJelz.setText("jLabel4");

        jLabel1.setText("Harcos Életerő:");

        jLabel3.setText("Varázsló Életerő:");

        HEleteroJelz.setText("jLabel2");

        javax.swing.GroupLayout EleterokPanelLayout = new javax.swing.GroupLayout(EleterokPanel);
        EleterokPanel.setLayout(EleterokPanelLayout);
        EleterokPanelLayout.setHorizontalGroup(
            EleterokPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EleterokPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(HEleteroJelz)
                .addGap(118, 118, 118)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(VEleteroJelz)
                .addContainerGap())
        );
        EleterokPanelLayout.setVerticalGroup(
            EleterokPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(EleterokPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(EleterokPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(HEleteroJelz)
                    .addComponent(jLabel3)
                    .addComponent(VEleteroJelz))
                .addContainerGap())
        );

        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton1.setMaximumSize(new java.awt.Dimension(100, 100));
        jButton1.setMinimumSize(new java.awt.Dimension(100, 100));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PalyaPanelLayout = new javax.swing.GroupLayout(PalyaPanel);
        PalyaPanel.setLayout(PalyaPanelLayout);
        PalyaPanelLayout.setHorizontalGroup(
            PalyaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PalyaPanelLayout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(32, Short.MAX_VALUE))
        );
        PalyaPanelLayout.setVerticalGroup(
            PalyaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PalyaPanelLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(PalyaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                    .addGroup(PalyaPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 150, Short.MAX_VALUE)
                        .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 182, Short.MAX_VALUE)
                .addComponent(PalyaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(175, 175, 175))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(EleterokPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(225, 225, 225))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(gombokPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(257, 257, 257))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(51, 51, 51)
                .addComponent(EleterokPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(41, 41, 41)
                .addComponent(PalyaPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(gombokPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(207, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(82, 82, 82)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void KovetkezoKorGombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KovetkezoKorGombActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_KovetkezoKorGombActionPerformed

    private void UjJatekGombActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UjJatekGombActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UjJatekGombActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel EleterokPanel;
    private javax.swing.JLabel HEleteroJelz;
    private javax.swing.JButton KovetkezoKorGomb;
    private javax.swing.JPanel PalyaPanel;
    private javax.swing.JButton UjJatekGomb;
    private javax.swing.JLabel VEleteroJelz;
    private javax.swing.JPanel gombokPanel;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
